"""
reset_and_seed.py — Limpia la base de conocimiento Notion y la llena
con contenido financiero relevante para la app Athena.

Uso:
    python reset_and_seed.py
"""
import os
import time
from dotenv import load_dotenv
from notion_client import Client

load_dotenv()
notion = Client(auth=os.getenv("NOTION_TOKEN"))
PARENT_ID = os.getenv("NOTION_PARENT_PAGE_ID")


# ── Helpers de bloques ────────────────────────────────────────────────────────

def h1(t):  return {"object":"block","type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":t}}]}}
def h2(t):  return {"object":"block","type":"heading_2","heading_2":{"rich_text":[{"type":"text","text":{"content":t}}]}}
def h3(t):  return {"object":"block","type":"heading_3","heading_3":{"rich_text":[{"type":"text","text":{"content":t}}]}}
def p(t):   return {"object":"block","type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":t}}]}}
def b(t):   return {"object":"block","type":"bulleted_list_item","bulleted_list_item":{"rich_text":[{"type":"text","text":{"content":t}}]}}
def n(t):   return {"object":"block","type":"numbered_list_item","numbered_list_item":{"rich_text":[{"type":"text","text":{"content":t}}]}}
def div():  return {"object":"block","type":"divider","divider":{}}
def callout(t, emoji="💡"): return {"object":"block","type":"callout","callout":{"rich_text":[{"type":"text","text":{"content":t}}],"icon":{"type":"emoji","emoji":emoji}}}


def crear_pagina_rica(parent_id, titulo, bloques):
    """Crea página con hasta 100 bloques por lote."""
    page = notion.pages.create(
        parent={"type": "page_id", "page_id": parent_id},
        properties={"title": [{"type": "text", "text": {"content": titulo}}]},
    )
    pid = page["id"]
    for i in range(0, len(bloques), 90):
        notion.blocks.children.append(block_id=pid, children=bloques[i:i+90])
        time.sleep(0.3)
    print(f"  ✓ {titulo}")
    return pid


# ── Paso 1: Eliminar hijos actuales ──────────────────────────────────────────

def eliminar_hijos(parent_id):
    print("🗑  Eliminando páginas existentes…")
    cursor = None
    while True:
        params = {"block_id": parent_id, "page_size": 100}
        if cursor:
            params["start_cursor"] = cursor
        resp = notion.blocks.children.list(**params)
        for blk in resp.get("results", []):
            if blk["type"] == "child_page":
                notion.pages.update(page_id=blk["id"], archived=True)
                print(f"  🗑 {blk['child_page']['title']}")
                time.sleep(0.2)
        if not resp.get("has_more"):
            break
        cursor = resp["next_cursor"]
    print("  Listo.\n")


# ── Paso 2: Páginas de conocimiento ──────────────────────────────────────────

PAGES = [

    ("💰 Finanzas Personales: Conceptos Fundamentales", [
        h1("Finanzas Personales: Conceptos Fundamentales"),
        callout("Dominar tus finanzas personales es la base para construir riqueza y libertad financiera.", "💰"),
        div(),
        h2("¿Qué son las finanzas personales?"),
        p("Las finanzas personales son la gestión del dinero de un individuo o familia: ingresos, gastos, ahorro, inversión y planificación para el futuro."),
        div(),
        h2("Los 5 pilares"),
        n("Ingresos: todo el dinero que entra (salario, freelance, rentas, inversiones)."),
        n("Gastos: todo lo que sale. Se dividen en fijos (renta, servicios) y variables (comida, entretenimiento)."),
        n("Ahorro: la diferencia entre ingresos y gastos. Mínimo recomendado: 20% del ingreso neto."),
        n("Inversión: hacer que el ahorro crezca más rápido que la inflación."),
        n("Protección: seguros, fondo de emergencia y diversificación."),
        div(),
        h2("Regla de oro"),
        callout("Gasta menos de lo que ganas. Invierte la diferencia.", "🏆"),
        div(),
        h2("Errores comunes"),
        b("No tener presupuesto ni registro de gastos."),
        b("Pagar solo el mínimo de la tarjeta de crédito."),
        b("No tener fondo de emergencia."),
        b("Empezar a invertir muy tarde (el tiempo es el activo más valioso)."),
        b("Confundir deseos con necesidades."),
    ]),

    ("📊 Control de Gastos: Presupuesto 50/30/20", [
        h1("Control de Gastos: Presupuesto 50/30/20"),
        callout("Un presupuesto no limita tu libertad, te la da.", "📊"),
        div(),
        h2("La Regla 50/30/20"),
        p("Divide tu ingreso NETO (después de impuestos) en tres categorías:"),
        b("50% — Necesidades: renta/hipoteca, supermercado, transporte, servicios básicos, salud esencial."),
        b("30% — Deseos: restaurantes, entretenimiento, ropa no esencial, viajes, suscripciones."),
        b("20% — Ahorro e inversión: fondo de emergencia, CETES, AFORE voluntario, pago de deudas extra."),
        div(),
        h2("Ejemplo con $20,000 MXN netos"),
        b("$10,000 → necesidades (renta $6,000 + comida $2,500 + transporte $1,500)"),
        b("$6,000 → deseos (salidas $2,500 + ropa $1,500 + streaming $500 + otros $1,500)"),
        b("$4,000 → ahorro/inversión ($2,000 CETES + $1,000 emergencias + $1,000 deuda extra)"),
        div(),
        h2("Pasos para crear tu presupuesto"),
        n("Registra TODOS tus ingresos netos mensuales."),
        n("Lista todos tus gastos fijos del mes."),
        n("Estima gastos variables con base en los últimos 3 meses."),
        n("Asigna cada gasto a necesidad, deseo o ahorro."),
        n("Ajusta hasta que los porcentajes se acerquen a 50/30/20."),
        n("Revisa y ajusta cada mes."),
        div(),
        callout("Tip: usa la app Athena para registrar cada gasto al momento. Lo que no se mide, no se controla.", "📱"),
        div(),
        h2("Alternativas al 50/30/20"),
        b("Método 80/20: guarda 20% automáticamente al recibir tu pago, gasta el resto."),
        b("Presupuesto base cero: asigna cada peso a una categoría hasta llegar a $0 disponible."),
        b("Método de sobres: retira efectivo y distribúyelo en sobres por categoría."),
    ]),

    ("💳 Buró de Crédito MX: Guía Completa", [
        h1("Buró de Crédito en México: Guía Completa"),
        callout("El Buró de Crédito NO es una lista negra. Es tu historial financiero completo.", "ℹ️"),
        div(),
        h2("¿Qué es el Buró de Crédito?"),
        p("El Buró de Crédito (Trans Union de México) es una empresa privada que recopila el historial crediticio de personas y empresas. Bancos, tiendas departamentales y financieras reportan mensualmente el comportamiento de pago de sus clientes."),
        div(),
        h2("¿Para qué sirve?"),
        b("Las instituciones financieras lo consultan antes de aprobar un crédito."),
        b("Determina la tasa de interés que te ofrecerán."),
        b("Personas con buen historial reciben mejores condiciones."),
        div(),
        h2("Los 5 factores del Score (400–850 puntos)"),
        b("35% — Historial de pagos: ¿Pagas a tiempo? Es el factor más importante. Un solo atraso puede bajar hasta 50 puntos."),
        b("30% — Utilización de crédito: Porcentaje de tu límite que usas. Ideal: mantener por debajo del 30%."),
        b("15% — Antigüedad crediticia: Cuánto tiempo llevas con créditos. Más tiempo = mejor score."),
        b("10% — Mix de créditos: Variedad de productos (tarjeta, auto, hipoteca). Más tipos = mejor."),
        b("10% — Nuevas solicitudes: Cada vez que solicitas un crédito, queda registro. Muchas solicitudes = riesgo."),
        div(),
        h2("Rangos del score"),
        b("400–579: Muy malo. Difícil acceder a créditos."),
        b("580–649: Malo. Solo créditos con garantía o tasas muy altas."),
        b("650–699: Regular. Créditos disponibles con tasas medias."),
        b("700–749: Bueno. Buenas condiciones y tasas competitivas."),
        b("750–850: Excelente. Acceso a las mejores tasas del mercado."),
        div(),
        h2("Cómo mejorar tu score"),
        n("Paga SIEMPRE a tiempo, aunque sea el mínimo."),
        n("Reduce la utilización de tus tarjetas por debajo del 30%."),
        n("No canceles tarjetas antiguas (reduce tu antigüedad crediticia)."),
        n("No solicites varios créditos en poco tiempo."),
        n("Diversifica: si solo tienes tarjeta, considera un crédito de auto o personal pequeño."),
        div(),
        callout("Tienes derecho a 1 reporte gratuito por año en burodecredito.com.mx. ¡Revísalo!", "🆓"),
    ]),

    ("🏛️ CETES: Inversión Sin Riesgo en México", [
        h1("CETES: Certificados de la Tesorería"),
        callout("CETES son la inversión más segura de México, respaldada por el Gobierno Federal.", "🏛️"),
        div(),
        h2("¿Qué son los CETES?"),
        p("Los Certificados de la Tesorería de la Federación (CETES) son instrumentos de deuda emitidos por el Gobierno Federal de México. Al comprar CETES, le prestas dinero al gobierno y él te paga intereses."),
        div(),
        h2("Características clave"),
        b("Emisor: Gobierno Federal de México (máxima seguridad)."),
        b("Rendimiento actual: ~10.5% anual (tasa variable, referenciada a la TIIE del Banxico)."),
        b("Plazos: 28, 91, 182 y 364 días."),
        b("Inversión mínima: $100 MXN en cetesdirecto.com.mx."),
        b("Disponibilidad: acceso al dinero al vencimiento del plazo elegido."),
        b("Impuestos: se cobra ISR sobre los rendimientos (tasa variable según el año)."),
        div(),
        h2("¿Cómo invertir en CETES?"),
        n("Entra a cetesdirecto.com.mx (plataforma oficial del gobierno)."),
        n("Regístrate con tu CURP, RFC y datos bancarios."),
        n("Elige el plazo: 28 días para liquidez, 364 días para mayor rendimiento."),
        n("Transfiere desde tu banco y compra."),
        n("Al vencimiento, el capital + intereses regresan a tu cuenta."),
        div(),
        h2("Comparativa vs ahorro bancario"),
        b("Cuenta de ahorro bancaria típica: 2-4% anual."),
        b("CETES 28 días: ~10.5% anual."),
        b("CETES 364 días: ~10.2% anual (ligeramente menor por expectativa de bajas en TIIE)."),
        div(),
        callout("Ejemplo: $10,000 MXN en CETES 28 días por 1 año generan ~$1,050 brutos. En banco: ~$200-400.", "💡"),
        div(),
        h2("Para quién es ideal"),
        b("Personas con perfil de riesgo bajo."),
        b("Para el fondo de emergencia (plazo 28 días = liquidez mensual)."),
        b("Primeros inversionistas en México."),
        b("Para ahorros de corto plazo con mejor rendimiento que el banco."),
    ]),

    ("🏦 SOFIPOS: Ahorro con Garantía del IPAB", [
        h1("SOFIPOS: Ahorro Seguro con Rendimiento"),
        callout("Las SOFIPOS ofrecen rendimientos de hasta 12% anual con garantía del IPAB hasta 25,000 UDIs.", "🏦"),
        div(),
        h2("¿Qué son las SOFIPOS?"),
        p("Las Sociedades Financieras Populares (SOFIPOS) son instituciones de ahorro reguladas por la CNBV. Captan depósitos del público y ofrecen rendimientos superiores a los bancos tradicionales."),
        div(),
        h2("Características"),
        b("Rendimiento típico: 10-14% anual (varía por institución y plazo)."),
        b("Garantía IPAB: hasta 25,000 UDIs (~$210,000 MXN aprox. 2024) por institución."),
        b("Reguladas por: CNBV y Comisión Nacional Bancaria y de Valores."),
        b("Acceso: muchas tienen apps móviles (Cuéntica, Klar, Finsus, Compartamos Banco)."),
        div(),
        h2("SOFIPOS conocidas en México"),
        b("Finsus: 11-13% anual, app sencilla, mínimo $1 MXN."),
        b("Cuéntica: ~12% anual, integración con transferencias SPEI."),
        b("Libertad Servicios Financieros: tradicional, atención en sucursal."),
        b("Came Caja Popular: cooperativa de ahorro."),
        div(),
        h2("SOFIPOS vs Bancos vs CETES"),
        b("Banco tradicional: 2-4% — alta liquidez, mínima rentabilidad."),
        b("CETES: ~10.5% — 100% seguro (gobierno), liquidez mensual."),
        b("SOFIPOS: 10-14% — garantía IPAB, mayor rendimiento, más riesgo institucional."),
        div(),
        callout("Diversifica: parte en CETES (gobierno), parte en SOFIPOS (rendimiento extra) y parte en inversión de mayor plazo.", "⚖️"),
    ]),

    ("📈 Inversiones en México: Panorama General", [
        h1("Inversiones en México: Panorama General"),
        callout("Invertir es hacer que tu dinero trabaje para ti mientras tú duermes.", "📈"),
        div(),
        h2("Pirámide de inversión por riesgo"),
        b("BASE (bajo riesgo): CETES, SOFIPOS, fondos gubernamentales. Rendimiento: 9-14% anual."),
        b("MEDIO (riesgo moderado): Fondos de inversión mixtos, ETFs, acciones de empresas estables. Rendimiento esperado: 7-15% anual."),
        b("ALTO (alto riesgo): Acciones individuales, criptomonedas, startups. Puede ganar o perder mucho."),
        div(),
        h2("S&P 500 desde México"),
        p("El índice S&P 500 agrupa a las 500 empresas más grandes de EE.UU. Su rendimiento histórico es ~10% anual en dólares."),
        b("Cómo invertir desde MX: GBM+, BIVA, Actinver, o plataformas como Charles Schwab."),
        b("Riesgo cambiario: ganas o pierdes también por el tipo de cambio MXN/USD."),
        b("Alternativa simple: ETF 'VOO' o 'SPY' que replica el S&P 500."),
        div(),
        h2("BMV e IPC mexicano"),
        b("El IPC (Índice de Precios y Cotizaciones) es el principal índice bursátil de México."),
        b("Rendimiento histórico: ~7% anual en pesos."),
        b("Acceso: GBM+, Kuspit, BBVA Patrimonios."),
        div(),
        h2("AFORE: tu pensión obligatoria"),
        b("Aportación obligatoria: ~6.5% patrón + ~1.125% trabajador + ~0.225% gobierno = ~7.85% de tu salario."),
        b("Puedes hacer aportaciones voluntarias para aumentar tu pensión o retirar en caso de desempleo."),
        b("Administrada por tu AFORE. Cámbiala si otra tiene mejores rendimientos en miafore.com.mx."),
        div(),
        h2("Pasos para empezar a invertir"),
        n("Antes de invertir: crea tu fondo de emergencia (3-6 meses de gastos)."),
        n("Paga deudas de alto costo (tarjetas >20% anual) primero."),
        n("Empieza con CETES Directo: seguro, simple, desde $100."),
        n("Aumenta aportaciones voluntarias a tu AFORE."),
        n("Explora fondos indexados (S&P 500) para inversión a largo plazo."),
    ]),

    ("🧮 Interés Compuesto: El Octavo Arte", [
        h1("Interés Compuesto: Por Qué el Tiempo es tu Mayor Activo"),
        callout("'El interés compuesto es la octava maravilla del mundo.' — Albert Einstein (atribuido)", "🧮"),
        div(),
        h2("¿Qué es?"),
        p("El interés compuesto es cuando los intereses generados se reinvierten y empiezan a generar sus propios intereses. Es el principio base de toda inversión a largo plazo."),
        div(),
        h2("Fórmula"),
        p("Valor final = P × (1 + r)^n + PMT × [(1+r)^n - 1] / r"),
        b("P = capital inicial"),
        b("r = tasa de interés por período (anual/12 si es mensual)"),
        b("n = número de períodos (meses o años)"),
        b("PMT = aportación periódica adicional"),
        div(),
        h2("El poder del tiempo: ejemplos"),
        b("$10,000 al 10% anual por 10 años = $25,937 (sin aportaciones extra)."),
        b("$10,000 al 10% anual por 20 años = $67,275."),
        b("$10,000 al 10% anual por 30 años = $174,494."),
        p("El tiempo multiplica el dinero de forma exponencial, no lineal."),
        div(),
        h2("Aportaciones mensuales: la verdadera magia"),
        b("$0 inicial + $1,000/mes al 10% por 20 años = $765,697."),
        b("$0 inicial + $2,000/mes al 10% por 20 años = $1,531,395."),
        div(),
        callout("Empezar 10 años antes duplica o triplica el resultado final. Empieza HOY aunque sea con poco.", "⏰"),
        div(),
        h2("Regla del 72"),
        p("Para saber en cuántos años se duplica tu dinero: divide 72 entre la tasa anual."),
        b("10% anual: se duplica en 72/10 = 7.2 años."),
        b("6% anual: se duplica en 72/6 = 12 años."),
        b("12% anual: se duplica en 72/12 = 6 años."),
    ]),

    ("🚨 Fondo de Emergencia: Base de tu Seguridad Financiera", [
        h1("Fondo de Emergencia"),
        callout("El fondo de emergencia no es un lujo, es la base de toda planificación financiera.", "🚨"),
        div(),
        h2("¿Qué es?"),
        p("Es una reserva de dinero en efectivo o inversión líquida destinada exclusivamente a cubrir imprevistos: pérdida de empleo, emergencia médica, reparación urgente de auto o casa."),
        div(),
        h2("¿Cuánto necesito?"),
        b("Mínimo: 3 meses de gastos fijos (renta + comida + servicios + transporte)."),
        b("Recomendado: 6 meses de gastos fijos."),
        b("Si eres freelance o autoempleado: 6-12 meses."),
        p("Ejemplo: si gastas $15,000 MXN/mes en necesidades básicas, tu fondo de emergencia ideal es $90,000 MXN."),
        div(),
        h2("¿Dónde guardar el fondo de emergencia?"),
        b("NO en efectivo en casa (inflación + riesgo de robo)."),
        b("CETES 28 días: disponible cada mes, rinde ~10.5% anual. Ideal."),
        b("SOFIPOS con retiro en 24-48 horas."),
        b("Cuenta de ahorro de alta tasa (solo si ofrece más de 5% anual)."),
        div(),
        h2("Cómo construirlo"),
        n("Calcula tus gastos fijos mensuales."),
        n("Define tu meta (3 o 6 meses)."),
        n("Ahorra un monto fijo cada quincena automáticamente."),
        n("Abre una cuenta separada específica para emergencias."),
        n("NO toques el fondo salvo verdaderas emergencias."),
        n("Cuando lo uses, repónlo antes de invertir de nuevo."),
        div(),
        callout("Si ya tienes fondo de emergencia, el 20% de ahorro mensual puede ir 100% a inversiones.", "💡"),
    ]),

    ("💸 Estrategias para Pagar Deudas", [
        h1("Estrategias para Eliminar Deudas"),
        callout("La mejor inversión que puedes hacer es pagar deudas con tasas de interés superiores a tus rendimientos posibles.", "💸"),
        div(),
        h2("¿Por qué las deudas son peligrosas?"),
        b("Una tarjeta de crédito puede cobrar 60-120% CAT anual."),
        b("Un préstamo de nómina: 40-80% CAT."),
        b("Mientras pagues esas tasas, ninguna inversión vale la pena."),
        div(),
        h2("Método Avalancha (mathematically optimal)"),
        p("Paga primero la deuda con la TASA DE INTERÉS MÁS ALTA, independientemente del saldo."),
        n("Lista todas tus deudas con su tasa CAT."),
        n("Paga el mínimo en todas."),
        n("Todo el dinero extra → a la deuda con mayor tasa."),
        n("Cuando se elimina, ese pago se agrega a la siguiente de mayor tasa."),
        p("Ventaja: pagas menos intereses en total. Desventaja: puede tomar tiempo antes de ver una deuda eliminada."),
        div(),
        h2("Método Bola de Nieve (psychological boost)"),
        p("Paga primero la deuda con el SALDO MÁS PEQUEÑO, independientemente de la tasa."),
        n("Lista deudas por saldo de menor a mayor."),
        n("Paga mínimo en todas."),
        n("Todo el dinero extra → a la deuda más pequeña."),
        n("Al eliminarla, suma ese pago a la siguiente más pequeña."),
        p("Ventaja: victorias rápidas que motivan. Desventaja: podrías pagar más intereses en total."),
        div(),
        h2("¿Cuál elegir?"),
        b("Si eres disciplinado y quieres optimizar: Avalancha."),
        b("Si necesitas motivación para no abandonar: Bola de Nieve."),
        div(),
        h2("Estrategia de consolidación"),
        b("Si tienes varias deudas altas, considera un crédito personal a tasa menor para consolidarlas."),
        b("Compara el CAT total antes de consolidar."),
        b("Cuidado: consolidar sin cambiar hábitos solo posterga el problema."),
        div(),
        callout("Regla: Nunca inviertas mientras tengas deudas con tasas superiores al 15% anual. Primero paga.", "⚠️"),
    ]),

    ("🏦 AFORE: Tu Pensión en México", [
        h1("AFORE: Administradora de Fondos para el Retiro"),
        callout("Tu AFORE trabaja para ti desde el primer día que cotizas en el IMSS. Cuídala.", "🏦"),
        div(),
        h2("¿Qué es una AFORE?"),
        p("Es una institución privada autorizada por el gobierno para administrar los ahorros de retiro de los trabajadores afiliados al IMSS o ISSSTE. Invierten tu dinero en activos financieros para hacerlo crecer hasta tu jubilación."),
        div(),
        h2("¿Cuánto va a mi AFORE?"),
        b("6.5% → patrón (cuota patronal)."),
        b("1.125% → trabajador (tú)."),
        b("0.225% → gobierno federal."),
        b("Total: ~7.875% de tu Salario Base de Cotización va a tu AFORE mensualmente."),
        div(),
        h2("SIEFORE: cómo se invierte tu dinero"),
        b("SIEFORE Básica de Pensiones (SB4): para trabajadores de 60+ años. Mayor proporción en renta fija."),
        b("SIEFORE Básica 3 (SB3): 46-59 años. Mixta entre renta fija y variable."),
        b("SIEFORE Básica 2 (SB2): 37-45 años. Mayor exposición a renta variable."),
        b("SIEFORE Básica 1 (SB1): hasta 36 años. Máxima exposición a renta variable para crecer más."),
        div(),
        h2("Aportaciones voluntarias"),
        b("Puedes aportar dinero extra en cualquier momento."),
        b("Deducibles de impuestos (ISR) hasta cierto límite."),
        b("Retirables: en caso de desempleo o retiro anticipado (con condiciones)."),
        b("Cómo: a través de la app/web de tu AFORE, en OXXO (con referencia), o en sucursal."),
        div(),
        h2("¿Cómo saber cuál AFORE tengo?"),
        p("Consulta e-SAR en e-sar.com.mx o llama a PROCESAR al 55 1328-5000."),
        div(),
        callout("Compara rendimientos en consar.gob.mx y cambia de AFORE si otra tiene mejor historial de rendimientos y menores comisiones.", "📊"),
    ]),

    ("📉 Inflación en México: Protege tu Dinero", [
        h1("Inflación en México: Cómo Protegerte"),
        callout("La inflación es el impuesto silencioso que nadie votó. Tu dinero en el banco pierde poder adquisitivo.", "📉"),
        div(),
        h2("¿Qué es la inflación?"),
        p("Es el aumento generalizado y sostenido de precios en una economía. Si la inflación es del 4% anual, lo que hoy cuesta $100 costará $104 el próximo año. Tu dinero vale menos."),
        div(),
        h2("Datos de México"),
        b("Objetivo del Banxico: 3% ± 1% (rango 2-4%)."),
        b("Inflación promedio 2020-2024: ~5-8% anual."),
        b("Medida por: INPC (Índice Nacional de Precios al Consumidor), publicado por INEGI."),
        div(),
        h2("Impacto en tus ahorros"),
        p("Si tu dinero está en una cuenta bancaria al 3% y la inflación es 5%, tu poder adquisitivo BAJA 2% al año."),
        b("Banco (3% rendimiento) - Inflación (5%) = -2% real."),
        b("CETES (10.5%) - Inflación (5%) = +5.5% real. ¡Esto sí genera riqueza!"),
        b("S&P 500 histórico (10% USD) + apreciación USD = variable, históricamente positivo en términos reales."),
        div(),
        h2("¿Cómo protegerse?"),
        b("No dejes efectivo estático: invierte en instrumentos que superen la inflación."),
        b("CETES ajustados por inflación (UDIBONOS): pagan inflación + tasa real."),
        b("Acciones e índices bursátiles: históricamente superan la inflación a largo plazo."),
        b("Bienes raíces: también tienden a subir con la inflación."),
        b("Dólares o activos en USD: protección si el peso se deprecia."),
        div(),
        callout("Regla práctica: Si tu inversión no supera la inflación + impuestos, estás perdiendo dinero en términos reales.", "💡"),
    ]),

    ("🏠 Crédito Hipotecario: INFONAVIT y FOVISSSTE", [
        h1("Crédito Hipotecario en México"),
        callout("Comprar casa es la mayor inversión de muchos mexicanos. Conoce tus opciones.", "🏠"),
        div(),
        h2("INFONAVIT"),
        b("Para trabajadores afiliados al IMSS (sector privado)."),
        b("Tasa de interés: 10.45% anual fija (trabajadores con VSM) o UDIS."),
        b("Requiere: cotizar continuamente, tener puntos INFONAVIT suficientes."),
        b("Crédito máximo 2024: ~$2.1 millones MXN dependiendo del salario."),
        b("Puedes combinar INFONAVIT + crédito bancario (cofinavit) para comprar más."),
        div(),
        h2("FOVISSSTE"),
        b("Para trabajadores del gobierno federal (ISSSTE)."),
        b("Tasa: UDIS + tasa real anual (~4%)."),
        b("Adjudicación: por sorteo o por puntos acumulados."),
        b("Proceso más lento que INFONAVIT, pero tasas competitivas."),
        div(),
        h2("Crédito bancario hipotecario"),
        b("Bancos (BBVA, Banorte, Santander, etc.): tasa desde ~10-13% anual con enganche 10-30%."),
        b("Ventaja: mayor monto y más rápido que INFONAVIT."),
        b("CAT debe ser menor al 15-18% para ser conveniente."),
        div(),
        h2("¿Comprar o rentar?"),
        p("Depende de: estabilidad laboral, ciudad, plazo de residencia y tasas actuales."),
        b("Rentar conviene si: ciudad cara, corto plazo (<5 años), tasas hipotecarias muy altas."),
        b("Comprar conviene si: plazo largo, acceso a INFONAVIT, construcción de patrimonio."),
        div(),
        callout("El CAT (Costo Anual Total) incluye tasa + comisiones + seguros. SIEMPRE compara CAT, no solo la tasa.", "⚠️"),
    ]),

    ("📱 Glosario Financiero: Términos Clave MX", [
        h1("Glosario Financiero Mexicano"),
        p("Términos que todo usuario de Athena debe conocer."),
        div(),
        h2("A - C"),
        b("AFORE: Administradora de Fondos para el Retiro. Gestiona tu pensión."),
        b("Banxico: Banco de México. Banco central, fija la tasa de interés de referencia (TIIE)."),
        b("Buró de Crédito: Empresa privada que guarda tu historial crediticio."),
        b("CAT: Costo Anual Total. Incluye tasa + comisiones + seguros. Sirve para comparar créditos."),
        b("CETES: Certificados de la Tesorería. Deuda del gobierno, inversión sin riesgo."),
        b("CNBV: Comisión Nacional Bancaria y de Valores. Regula bancos y casas de bolsa."),
        b("CONDUSEF: Comisión Nacional para la Protección y Defensa de los Usuarios de Servicios Financieros. Defensa del consumidor."),
        div(),
        h2("D - I"),
        b("ETF: Exchange Traded Fund. Fondo que cotiza en bolsa y replica un índice (ej. S&P 500)."),
        b("FOVISSSTE: Fondo de Vivienda para trabajadores del gobierno (ISSSTE)."),
        b("IPC: Índice de Precios y Cotizaciones de la BMV. Principal índice bursátil de México."),
        b("INFONAVIT: Instituto del Fondo Nacional de la Vivienda para los Trabajadores."),
        b("INPC: Índice Nacional de Precios al Consumidor. Mide la inflación (INEGI)."),
        b("IPAB: Instituto para la Protección al Ahorro Bancario. Garantiza depósitos hasta 400,000 UDIS."),
        b("ISR: Impuesto Sobre la Renta. Se cobra sobre tus rendimientos de inversión."),
        div(),
        h2("P - U"),
        b("PMT: Pago mensual o aportación periódica en fórmulas financieras."),
        b("ROI: Return on Investment. Porcentaje de ganancia respecto al capital invertido."),
        b("SAT: Servicio de Administración Tributaria. Autoridad fiscal de México."),
        b("SIEFORE: Sociedad de Inversión Especializada en Fondos para el Retiro. Fondos dentro de tu AFORE."),
        b("SOFIPO: Sociedad Financiera Popular. Institución de ahorro regulada por CNBV."),
        b("TIIE: Tasa de Interés Interbancaria de Equilibrio. Tasa de referencia de Banxico (~11% en 2024)."),
        b("UDI: Unidad de Inversión. Valor indexado a la inflación. 1 UDI ≈ $8.50 MXN (2024)."),
    ]),

    ("🎯 Metas Financieras SMART", [
        h1("Metas Financieras SMART"),
        callout("Una meta financiera sin fecha y monto específico es solo un sueño.", "🎯"),
        div(),
        h2("¿Qué es una meta SMART?"),
        b("S — Específica: ¿Cuánto dinero y para qué exactamente?"),
        b("M — Medible: ¿Cómo sabrás que la alcanzaste?"),
        b("A — Alcanzable: ¿Es posible con tus ingresos actuales?"),
        b("R — Relevante: ¿Importa realmente en tu vida?"),
        b("T — Con tiempo: ¿Cuándo exactamente la quieres lograr?"),
        div(),
        h2("Ejemplos de metas financieras SMART"),
        b("'Ahorro' → NO SMART."),
        b("'Ahorrar $50,000 para el enganche de un coche para diciembre 2025, guardando $4,200/mes' → SMART."),
        b("'Invertir $3,000 al mes en CETES durante 24 meses para llegar a $80,000 de fondo de emergencia' → SMART."),
        div(),
        h2("Tipos de metas por plazo"),
        b("Corto plazo (< 1 año): fondo de emergencia, vacaciones, regalo especial."),
        b("Mediano plazo (1-5 años): enganche de auto o casa, negocio propio, maestría."),
        b("Largo plazo (5+ años): retiro, educación de hijos, independencia financiera."),
        div(),
        h2("Cómo calcular cuánto ahorrar"),
        p("Meta: $100,000 MXN en 12 meses. Si inviertes en CETES al 10.5% anual (~0.875% mensual):"),
        b("Aportación mensual necesaria: ~$7,950 MXN/mes."),
        b("Sin inversión (ahorro puro): $8,333 MXN/mes."),
        b("Diferencia a tu favor por el interés: ~$4,600 MXN al final."),
        div(),
        callout("Usa la sección de Inversión en Athena para calcular cuánto necesitas aportar mensualmente según tu meta y plazo.", "📱"),
    ]),

    ("🇲🇽 Sistema Financiero Mexicano: Panorama", [
        h1("Sistema Financiero Mexicano"),
        callout("Conocer las instituciones que regulan tus finanzas te protege y empodera.", "🇲🇽"),
        div(),
        h2("Autoridades reguladoras"),
        b("Banxico (Banco de México): banco central, controla la política monetaria, fija la TIIE, emite billetes."),
        b("CNBV (Comisión Nacional Bancaria y de Valores): supervisa bancos, casas de bolsa, SOFIPOS, AFORE."),
        b("CNSF (Comisión Nacional de Seguros y Fianzas): regula aseguradoras."),
        b("CONSAR (Comisión Nacional del Sistema de Ahorro para el Retiro): supervisa AFOREs."),
        b("CONDUSEF: protege a los usuarios de servicios financieros. Recibe quejas."),
        b("SAT (Servicio de Administración Tributaria): recauda impuestos."),
        div(),
        h2("Instituciones de protección al ahorro"),
        b("IPAB: garantiza depósitos en bancos y SOFIPOS hasta 400,000 UDIs (~$3.4M MXN) o 25,000 UDIs en SOFIPOS."),
        b("Si tu banco quiebra, el IPAB te devuelve hasta ese monto."),
        div(),
        h2("Instituciones de crédito principales"),
        b("BBVA México, Banorte, Santander México, HSBC, Citibanamex — bancos con mayor participación."),
        b("INFONAVIT, FOVISSSTE — crédito hipotecario para trabajadores."),
        b("NAFIN (Nacional Financiera) — financiamiento a PyMEs."),
        div(),
        h2("Fintechs reguladas en México"),
        b("La Ley FinTech (2018) regula instituciones de fondos de pago electrónico, crowdfunding y activos virtuales."),
        b("Entidades como Nu Bank, Clip, Kueski operan bajo esta regulación."),
        b("Verifica siempre que una fintech tenga registro en CNBV antes de depositar."),
        div(),
        callout("Antes de contratar cualquier servicio financiero, verifica en CNBV.gob.mx que la institución esté autorizada.", "✅"),
    ]),

    ("💡 Tips Financieros para Jóvenes Profesionistas MX", [
        h1("Tips Financieros para Jóvenes Profesionistas en México"),
        callout("Los hábitos financieros que formas hoy determinan tu libertad financiera en 20 años.", "💡"),
        div(),
        h2("Los 10 mandamientos financieros para empezar"),
        n("Abre una cuenta de ahorro separada para emergencias desde tu primer sueldo."),
        n("Automatiza el ahorro: el día de quincena, transfiere el 20% antes de gastar."),
        n("Evita deudas de consumo (tarjeta de crédito al tope, créditos de tiendas)."),
        n("Usa la tarjeta de crédito como herramienta: paga TODO el saldo cada mes."),
        n("Aumenta tus aportaciones voluntarias al AFORE cada año de aumento."),
        n("Lee un libro de finanzas personales al año (Padre Rico Padre Pobre, El Hombre Más Rico de Babilonia, Dinero: Domina el Juego)."),
        n("Invierte en tu educación: un curso o certificación que aumente tu sueldo tiene el mejor ROI."),
        n("Compara antes de contratar: seguro, crédito, banco. El CAT no miente."),
        n("Declara ante el SAT si tus ingresos anuales superan $400,000 o si tienes ingresos por honorarios."),
        n("Habla de dinero con tu pareja antes de casarte: la incompatibilidad financiera es causa #1 de divorcios."),
        div(),
        h2("Error #1 de los millennials mexicanos"),
        p("Pensar que 'después' empezarán a ahorrar e invertir. El costo de esperar 10 años puede ser más de $1 millón MXN en valor futuro."),
        div(),
        callout("Empieza con $200/mes en CETES si es lo único posible. Lo importante es el hábito, no el monto inicial.", "🌱"),
    ]),

    ("🔢 Calculadora de Inversión: Cómo Interpretar tus Resultados", [
        h1("Cómo Usar e Interpretar la Calculadora de Inversión de Athena"),
        callout("La calculadora de Athena usa la fórmula de interés compuesto con aportaciones periódicas.", "🔢"),
        div(),
        h2("Parámetros de la calculadora"),
        b("Inversión inicial (P): capital con el que empiezas. Puede ser $0."),
        b("Aportación mensual (PMT): cuánto agregas cada mes. Constancia > monto inicial."),
        b("Tasa anual (%): rendimiento esperado por año. Se convierte a mensual internamente."),
        b("Plazo (años): tiempo de la inversión. Más plazo = más interés compuesto."),
        div(),
        h2("Tasas de referencia (México, 2024)"),
        b("CETES Directo: ~10.5% anual. Riesgo: mínimo (gobierno federal)."),
        b("SOFIPOS (Finsus, Cuéntica): ~12% anual. Riesgo: bajo (IPAB garantiza hasta 25,000 UDIs)."),
        b("Fondo gubernamental: ~9% anual. Riesgo: muy bajo."),
        b("S&P 500 histórico: ~10% anual en USD. Riesgo: medio (fluctúa mucho año a año)."),
        b("BMV/IPC histórico: ~7% anual en MXN. Riesgo: medio."),
        b("Cuenta bancaria: 2-4% anual. Riesgo: muy bajo pero no supera inflación."),
        b("Bajo el colchón: 0% (pierde con inflación ~5% anual)."),
        div(),
        h2("¿Qué significan ROI y ganancia?"),
        b("Ganancia = Valor final - Total aportado (inicial + aportaciones × meses)."),
        b("ROI = Ganancia / Total aportado × 100. Ejemplo: ROI 150% significa que ganaste 1.5x lo invertido."),
        div(),
        h2("Advertencias importantes"),
        b("Las tasas históricas NO garantizan rendimientos futuros."),
        b("La inflación reduce el poder adquisitivo real de tus ganancias."),
        b("Considera el ISR sobre rendimientos (aproximadamente 0.15% mensual en CETES)."),
        b("Para S&P 500, el riesgo cambiario MXN/USD puede afectar significativamente."),
        div(),
        callout("Consejo: usa la comparativa de instrumentos de la app para ver en un vistazo qué instrumento te da más en tu plazo específico.", "📱"),
    ]),

    ("📊 Flujo de Efectivo: Tu Película Financiera Mensual", [
        h1("Flujo de Efectivo: Entiende tu Película Financiera"),
        callout("El balance bancario es una foto. El flujo de efectivo es la película completa de tu mes.", "📊"),
        div(),
        h2("¿Qué es el flujo de efectivo personal?"),
        p("Es el registro de TODO el dinero que entra y sale en un período. Te dice si estás generando o consumiendo riqueza mes a mes."),
        div(),
        h2("Flujo positivo vs negativo"),
        b("Flujo positivo: ingresos > gastos. Generas riqueza, puedes invertir o ahorrar."),
        b("Flujo negativo: gastos > ingresos. Te endeudas o reduces ahorros. Señal de alerta."),
        div(),
        h2("Cómo registrar tu flujo en Athena"),
        n("Abre la sección de Finanzas."),
        n("Registra CADA ingreso cuando entra (salario, freelance, transferencias)."),
        n("Registra CADA gasto al momento de pagarlo con su categoría correcta."),
        n("Revisa el resumen del mes en la parte superior (Ingresos / Gastos / Balance)."),
        n("Al final del mes, analiza qué categorías consumieron más."),
        div(),
        h2("Patrones a identificar"),
        b("¿Qué categorías se llevan más del 50% de tus gastos?"),
        b("¿Hay gastos recurrentes que no recuerdas haber autorizado (suscripciones olvidadas)?"),
        b("¿Cuál es tu 'fuga' principal? (generalmente entretenimiento o comida fuera de casa)"),
        b("¿Tu balance del mes es positivo o negativo consistentemente?"),
        div(),
        callout("La conciencia financiera es el primer paso. Solo al registrar puedes mejorar.", "✍️"),
    ]),

]


# ── Paso 3: Ejecutar ──────────────────────────────────────────────────────────

def main():
    if not PARENT_ID:
        print("ERROR: NOTION_PARENT_PAGE_ID no está configurado en .env")
        return

    eliminar_hijos(PARENT_ID)

    print(f"📚 Creando {len(PAGES)} páginas de base de conocimiento financiero…\n")
    for titulo, bloques in PAGES:
        crear_pagina_rica(PARENT_ID, titulo, bloques)
        time.sleep(0.4)

    print(f"\n✅ Base de conocimiento creada con {len(PAGES)} páginas.")


if __name__ == "__main__":
    main()
